"""Backend metadata for ``networkx.backend_info``.

This module must stay importable without importing NetworkX, since NetworkX
reads it while it is still being imported.
"""

FUNCTIONS = {
    "all_pairs_dijkstra": {},
    "all_pairs_dijkstra_path": {},
    "all_pairs_dijkstra_path_length": {},
    "all_pairs_shortest_path": {},
    "all_pairs_shortest_path_length": {},
    "all_shortest_paths": {},
    "ancestors": {},
    "articulation_points": {},
    "attracting_components": {},
    "average_clustering": {},
    "average_shortest_path_length": {},
    "betweenness_centrality": {},
    "betweenness_centrality_subset": {},
    "bfs_edges": {},
    "bfs_layers": {},
    "bfs_predecessors": {},
    "bfs_successors": {},
    "bfs_tree": {},
    "biconnected_component_edges": {},
    "biconnected_components": {},
    "bidirectional_dijkstra": {},
    "bidirectional_shortest_path": {},
    "center": {},
    "closeness_centrality": {},
    "clustering": {},
    "connected_components": {},
    "core_number": {},
    "degree_centrality": {},
    "descendants": {},
    "descendants_at_distance": {},
    "dfs_edges": {},
    "dfs_postorder_nodes": {},
    "dfs_predecessors": {},
    "dfs_preorder_nodes": {},
    "dfs_successors": {},
    "dfs_tree": {},
    "diameter": {},
    "dijkstra_path": {},
    "dijkstra_path_length": {},
    "dispersion": {},
    "eccentricity": {},
    "edge_betweenness_centrality": {},
    "edge_betweenness_centrality_subset": {},
    "edge_load_centrality": {},
    "eigenvector_centrality": {},
    "global_reaching_centrality": {},
    "greedy_color": {},
    "group_betweenness_centrality": {},
    "group_closeness_centrality": {},
    "group_degree_centrality": {},
    "group_in_degree_centrality": {},
    "group_out_degree_centrality": {},
    "harmonic_centrality": {},
    "has_path": {},
    "in_degree_centrality": {},
    "is_attracting_component": {},
    "is_biconnected": {},
    "is_bipartite": {},
    "is_connected": {},
    "is_directed_acyclic_graph": {},
    "is_forest": {},
    "is_strongly_connected": {},
    "is_tree": {},
    "is_weakly_connected": {},
    "k_core": {},
    "katz_centrality": {},
    "label_propagation_communities": {},
    "local_reaching_centrality": {},
    "maximum_spanning_edges": {},
    "maximum_spanning_tree": {},
    "minimum_spanning_edges": {},
    "minimum_spanning_tree": {},
    "newman_betweenness_centrality": {},
    "node_connected_component": {},
    "number_attracting_components": {},
    "number_connected_components": {},
    "number_strongly_connected_components": {},
    "number_weakly_connected_components": {},
    "out_degree_centrality": {},
    "pagerank": {},
    "percolation_centrality": {},
    "periphery": {},
    "prominent_group": {},
    "radius": {},
    "shortest_path": {},
    "shortest_path_length": {},
    "single_source_dijkstra": {},
    "single_source_dijkstra_path": {},
    "single_source_dijkstra_path_length": {},
    "single_source_shortest_path": {},
    "single_source_shortest_path_length": {},
    "single_target_shortest_path": {},
    "strongly_connected_components": {},
    "topological_generations": {},
    "topological_sort": {},
    "transitivity": {},
    "triangles": {},
    "voterank": {},
    "weakly_connected_components": {},
    "wiener_index": {},
}


def get_info():
    return {
        "backend_name": "rustnx",
        "project": "rustnx",
        "package": "rustnx",
        "short_summary": "Rust-accelerated algorithms, no code changes needed.",
        "functions": FUNCTIONS,
        "default_config": {},
    }
