[package]
name = "rustnx"
version = "0.1.0-alpha.3"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Fabuseless"]
description = "Rust-accelerated backend for NetworkX"
repository = "https://github.com/fabuseless/rustnx"
homepage = "https://github.com/fabuseless/rustnx"
readme = "README.md"
publish = false

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py310"] }
rayon = "1"
quick-xml = "0.38"

[profile.release]
lto = "fat"
codegen-units = 1
